name: cd-android
on:
  push:
    branches: [feat/main]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Permisos
      run: chmod +x gradlew
    - name: build release 
      run: ./gradlew build
    - name: build release 
      run: ./gradlew assembleRelease
    - name: upload-artifact-apk
      uses: actions/upload-artifact@v1
      with:
          name: APK
          path: app/build/outputs/apk/debug/app-debug.apk
    - name: build release 
      run: ./gradlew app:bundleRelease
    - name: Sign AAB
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: upload-artifact-aab
      uses: actions/upload-artifact@v1
      with:
          name: AAB
          path: app/build/outputs/bundle/release/app-release.aab
  prd:
    runs-on: ubuntu-latest
    needs: [build]
    if: |
         always() &&
         github.event_name == 'push'  &&
         github.ref == 'refs/heads/feat/main' &&
         needs.build.result == 'success'
    steps:
    - name: Download from build APK
      uses: actions/download-artifact@v1
      with:
        name: APK
    - run: ls APK
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: 1:703012472585:android:4fb4914151594279cbf5d8
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: APK/app-debug.apk
    - name: Download from build AAB
      uses: actions/download-artifact@v1
      with:
        name: AAB
    - run: ls
    - name: Upload App Bundle
      uses: actions/upload-artifact@v1
      with:
          name: aab-build
          path: AAB/app-release.aab
          retention-days: 7
    - name: Deploy to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        packageName: com.devopstools.app
        releaseFiles: AAB/app-release.aab
        track: internal